/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clusters */
        get: operations["list_clusters_api_clusters_get"];
        put?: never;
        /** Create Cluster */
        post: operations["create_cluster_api_clusters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clusters/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Connection
         * @description Connectivity check from unsaved form values; `existing` supplies blank secrets (edit).
         */
        post: operations["test_connection_api_clusters_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clusters/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cluster */
        get: operations["get_cluster_api_clusters__name__get"];
        /** Update Cluster */
        put: operations["update_cluster_api_clusters__name__put"];
        post?: never;
        /** Delete Cluster */
        delete: operations["delete_cluster_api_clusters__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clusters/{name}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connect Cluster */
        post: operations["connect_cluster_api_clusters__name__connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clusters/{name}/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disconnect Cluster */
        post: operations["disconnect_cluster_api_clusters__name__disconnect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CertView */
        CertView: {
            /** Subject */
            subject: string;
            /**
             * Not After
             * Format: date-time
             */
            not_after: string;
        };
        /**
         * ClusterInput
         * @description API create/update body; carries write-only secrets that are never persisted in YAML.
         */
        ClusterInput: {
            /** Name */
            name: string;
            /** Env */
            env: string;
            /** Region */
            region?: string | null;
            /** Bootstrap Servers */
            bootstrap_servers: string;
            /**
             * Security Protocol
             * @default PLAINTEXT
             * @enum {string}
             */
            security_protocol: "PLAINTEXT" | "SSL" | "SASL_PLAINTEXT" | "SASL_SSL";
            /** Sasl Mechanism */
            sasl_mechanism?: ("PLAIN" | "SCRAM-SHA-256" | "SCRAM-SHA-512") | null;
            /** Sasl Username */
            sasl_username?: string | null;
            /**
             * Read Only
             * @default false
             */
            read_only: boolean;
            /** Extra */
            extra?: {
                [key: string]: string;
            };
            /** Sasl Password */
            sasl_password?: string | null;
            /** Truststore Base64 */
            truststore_base64?: string | null;
            /** Truststore Password */
            truststore_password?: string | null;
        };
        /** ClusterView */
        ClusterView: {
            /** Name */
            name: string;
            /** Env */
            env: string;
            /** Region */
            region: string | null;
            /** Bootstrap Servers */
            bootstrap_servers: string;
            /**
             * Security Protocol
             * @enum {string}
             */
            security_protocol: "PLAINTEXT" | "SSL" | "SASL_PLAINTEXT" | "SASL_SSL";
            /** Sasl Mechanism */
            sasl_mechanism: ("PLAIN" | "SCRAM-SHA-256" | "SCRAM-SHA-512") | null;
            /** Sasl Username */
            sasl_username: string | null;
            /** Has Sasl Password */
            has_sasl_password: boolean;
            /** Read Only */
            read_only: boolean;
            /** Extra */
            extra: {
                [key: string]: string;
            };
            /** Truststore */
            truststore: components["schemas"]["CertView"][] | null;
            /** Usable */
            usable: boolean;
            /** Unusable Reason */
            unusable_reason: string | null;
            /** Connected */
            connected: boolean;
        };
        /** ConnectionTestResult */
        ConnectionTestResult: {
            /** Ok */
            ok: boolean;
        };
        /** ConnectionView */
        ConnectionView: {
            /** Name */
            name: string;
            /** Env */
            env: string;
            /** Region */
            region: string | null;
            /** Bootstrap Servers */
            bootstrap_servers: string;
            /** Read Only */
            read_only: boolean;
            /**
             * Connected At
             * Format: date-time
             */
            connected_at: string;
            /** Active Streams */
            active_streams: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** StatusView */
        StatusView: {
            /** Connections */
            connections: components["schemas"]["ConnectionView"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_clusters_api_clusters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterView"][];
                };
            };
        };
    };
    create_cluster_api_clusters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClusterInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_connection_api_clusters_test_post: {
        parameters: {
            query?: {
                existing?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClusterInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cluster_api_clusters__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_cluster_api_clusters__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClusterInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_cluster_api_clusters__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_cluster_api_clusters__name__connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_cluster_api_clusters__name__disconnect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusView"];
                };
            };
        };
    };
}
